{{- if .Values.wellknown.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wellknown.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "wellknown.labels" . | nindent 4 }}
data:
  server: |
    {{- tpl ( .Values.wellknown.server | toJson ) . | nindent 4 }}

  client: |
    {{- tpl ( .Values.wellknown.client | toJson ) . | nindent 4 }}
{{- end }}