{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "labels" . | nindent 4 }}
stringData: 
  {{- range $name, $data := .Values.secrets.files }}
  {{ $name }}: | {{ $data | nindent 4 }}
  {{- end }}
{{- end }}