workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

stages:
  - package
  - test

include:
  - component: $CI_SERVER_FQDN/gitlabci-components/helm-build/build@1.1.0
    inputs:
      name: matrix
      tag_name_postfix: ""
  - component: $CI_SERVER_FQDN/gitlabci-components/helm-build/build@1.1.0
    inputs:
      name: element
      tag_name_postfix: ""
  - component: $CI_SERVER_FQDN/gitlabci-components/helm-build/build@1.1.0
    inputs:
      name: sygnal
      tag_name_postfix: ""
  - component: $CI_SERVER_FQDN/gitlabci-components/helm-build/build@1.1.0
    inputs:
      name: livekit-jwt
      tag_name_postfix: ""
  - component: $CI_SERVER_FQDN/gitlabci-components/helm-build/build@1.1.0
    inputs:
      name: element-call
      tag_name_postfix: ""
  - component: $CI_SERVER_FQDN/gitlabci-components/helm-build/build@1.1.0
    inputs:
      name: ma1sd
      tag_name_postfix: ""
  - component: $CI_SERVER_FQDN/gitlabci-components/image-build-multiplatform/build@1
    inputs:
      name: ma1sd
      image_repos:
        - registry.rz1.metaways.net/devops
  - component: $CI_SERVER_FQDN/gitlabci-components/image-build-multiplatform/build@1
    inputs:
      name: synapse
      image_repos:
        - registry.rz1.metaways.net/devops

test-deploy:
  stage: test
  image: ghcr.io/helmfile/helmfile:v0.162.0
  environment:
    name: test-$CI_COMMIT_REF_SLUG
    url: https://element.$CI_COMMIT_REF_SLUG.$TEST_DEPLOY_BASE_DOMAIN
    deployment_tier: development
    on_stop: test-deploy-teardown
  variables:
    DEPLOYMENT_NAME: $CI_COMMIT_REF_SLUG
    MATRIX_CHART: matrix-registry/matrix
    ELEMENT_CHART: matrix-registry/element
    SYGNAL_CHART: matrix-registry/sygnal
    KUBE_CONTEXT: se/agent:ebhh-test
  before_script:
    - helm registry login "${CI_REGISTRY}" -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}"
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
    - kubectl config use-context $TEST_DEPLOY_AGENT_CONTEXT
  script:
    - export MATRIX_CHART_VERSION=0.0.0+mw0sha${CI_COMMIT_SHORT_SHA}
    - export ELEMENT_CHART_VERSION=0.0.0+mw0sha${CI_COMMIT_SHORT_SHA}
    - export SYGNAL_CHART_VERSION=0.0.0+mw0sha${CI_COMMIT_SHORT_SHA}
    - task test-deploy
    - task test-deploy:init-corporal-policy || (sleep 30; task test-deploy:init-corporal-policy)
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test-deploy-teardown:
  stage: test
  image: ghcr.io/helmfile/helmfile:v0.162.0
  environment:
    name: test-$CI_COMMIT_REF_SLUG
    action: stop
  variables:
    DEPLOYMENT_NAME: $CI_COMMIT_REF_SLUG
    MATRIX_CHART: matrix-registry/matrix
    ELEMENT_CHART: matrix-registry/element
    SYGNAL_CHART: matrix-registry/sygnal
    KUBE_CONTEXT: se/agent:ebhh-test
  before_script:
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
    - kubectl config use-context $TEST_DEPLOY_AGENT_CONTEXT
  script:
    - export MATRIX_CHART_VERSION=0.0.0+mw0sha${CI_COMMIT_SHORT_SHA}
    - export ELEMENT_CHART_VERSION=0.0.0+mw0sha${CI_COMMIT_SHORT_SHA}
    - export SYGNAL_CHART_VERSION=0.0.0+mw0sha${CI_COMMIT_SHORT_SHA}
    - task test-deploy:teardown
  when: manual
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"