workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

stages:
  - package
  - test

include:
  - component: $CI_SERVER_FQDN/gitlabci-components/helm-build/build@1.1.0
    inputs:
      name: matrix
      tag_name_postfix: ""
  - component: $CI_SERVER_FQDN/gitlabci-components/helm-build/build@1.1.0
    inputs:
      name: element
      tag_name_postfix: ""
  - component: $CI_SERVER_FQDN/gitlabci-components/helm-build/build@1.1.0
    inputs:
      name: sygnal
      tag_name_postfix: ""
  - component: $CI_SERVER_FQDN/gitlabci-components/helm-build/build@1.1.0
    inputs:
      name: livekit-jwt
      tag_name_postfix: ""
  - component: $CI_SERVER_FQDN/gitlabci-components/helm-build/build@1.1.0
    inputs:
      name: element-call
      tag_name_postfix: ""
  - component: $CI_SERVER_FQDN/gitlabci-components/helm-build/build@1.1.0
    inputs:
      name: ma1sd
      tag_name_postfix: ""
  - component: $CI_SERVER_FQDN/gitlabci-components/image-build/build@1.0.0
    inputs:
      name: ma1sd
      registry: registry.rz1.metaways.net
      registry_repo: registry.rz1.metaways.net/devops
      registry_user: $REGISTRY_RZ1_USER
      registry_password: $REGISTRY_RZ1_PASSWORD

build-synapse-image:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:v1.15.0-debug
    entrypoint: [ "sh", "-c" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - export SYNAPSE_VERSION=$(cat docker/synapse/.meta/tag)
    - export IMAGE_VERSION=$(echo "${CI_COMMIT_TAG:-synapse-image-${SYNAPSE_VERSION}-sha${CI_COMMIT_SHORT_SHA}}" | cut -b 15-)
    - |
      if [[ "${IMAGE_VERSION}" != ${SYNAPSE_VERSION}* ]]; then
        echo tag image version incorrect:
        echo "CI_COMMIT_TAG: ${CI_COMMIT_TAG} IMAGE_VERSION: ${IMAGE_VERSION} synapse version: ${SYNAPSE_VERSION}"
        echo "tag should be: synapse-image-<synapse source image version starting with v>-mw<build counter starting with 1>"
        echo "synapse version is set in docker/synapse/.meta/tag"
        exit 1
      fi
    - >-
      /kaniko/executor
      --skip-unused-stages
      --use-new-run
      --context "${CI_PROJECT_DIR}"
      --dockerfile docker/synapse/Dockerfile
      --build-arg SYNAPSE_VERSION
      --destination "${CI_REGISTRY_IMAGE}/synapse:${IMAGE_VERSION}"
  rules:
    - if: $CI_COMMIT_TAG =~ /^synapse-image-v.*/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test-deploy:
  stage: test
  image: ghcr.io/helmfile/helmfile:v0.162.0
  environment:
    name: test-$CI_COMMIT_REF_SLUG
    url: https://element.$CI_COMMIT_REF_SLUG.$TEST_DEPLOY_BASE_DOMAIN
    deployment_tier: development
    on_stop: test-deploy-teardown
  variables:
    DEPLOYMENT_NAME: $CI_COMMIT_REF_SLUG
    MATRIX_CHART: matrix-registry/matrix
    ELEMENT_CHART: matrix-registry/element
    SYGNAL_CHART: matrix-registry/sygnal
    KUBE_CONTEXT: se/agent:ebhh-test
  before_script:
    - helm registry login "${CI_REGISTRY}" -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}"
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
    - kubectl config use-context $TEST_DEPLOY_AGENT_CONTEXT
  script:
    - export MATRIX_CHART_VERSION=0.0.0+mw0sha${CI_COMMIT_SHORT_SHA}
    - export ELEMENT_CHART_VERSION=0.0.0+mw0sha${CI_COMMIT_SHORT_SHA}
    - export SYGNAL_CHART_VERSION=0.0.0+mw0sha${CI_COMMIT_SHORT_SHA}
    - task test-deploy
    - task test-deploy:init-corporal-policy || (sleep 30; task test-deploy:init-corporal-policy)
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test-deploy-teardown:
  stage: test
  image: ghcr.io/helmfile/helmfile:v0.162.0
  environment:
    name: test-$CI_COMMIT_REF_SLUG
    action: stop
  variables:
    DEPLOYMENT_NAME: $CI_COMMIT_REF_SLUG
    MATRIX_CHART: matrix-registry/matrix
    ELEMENT_CHART: matrix-registry/element
    SYGNAL_CHART: matrix-registry/sygnal
    KUBE_CONTEXT: se/agent:ebhh-test
  before_script:
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
    - kubectl config use-context $TEST_DEPLOY_AGENT_CONTEXT
  script:
    - export MATRIX_CHART_VERSION=0.0.0+mw0sha${CI_COMMIT_SHORT_SHA}
    - export ELEMENT_CHART_VERSION=0.0.0+mw0sha${CI_COMMIT_SHORT_SHA}
    - export SYGNAL_CHART_VERSION=0.0.0+mw0sha${CI_COMMIT_SHORT_SHA}
    - task test-deploy:teardown
  when: manual
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"