synapse:
  homeserverConfig:    
    # document that this is needed for matrix corporal or inject everything inside the entrypoint
    modules:
    - module: shared_secret_authenticator.SharedSecretAuthProvider
      config:
        m_login_password_support_enabled: true
        # shared_secret: is injected by the entrypoint

    oidc_providers:
    - idp_id: dex
      idp_name: "My Dex server"
      issuer: "https://{{ .Values.oauth.issuer }}"
      client_id: "synapse"
      client_secret: "{{ .Values.oauth.secret }}"
      scopes: ["openid", "profile"]
      user_mapping_provider:
        config:
          localpart_template: '{{ "{{" }} user.name {{ "}}" }}'
          display_name_template: '{{ "{{" }} user.name|capitalize {{ "}}" }}'
      # important: allows existing user to use oauth without manually changing the external id
      allow_existing_users: true

    sso:
      client_whitelist:
        - https://{{ .Values.element.ingress.hostname }}/
    update_profile_information: true

  logConfig:
    loggers:
      shared_secret_authenticator:
        level: INFO

corporal:
  enabled: true