https:
  enabled: false

config:
  storage:
    type: memory

  logger:
    level: "debug"

  connectors:

  oauth2:
    skipApprovalScreen: true

  enablePasswordDB: true

  staticPasswords:
  - email: "dex1@example.com"
    # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "dex1"
    userID: "11111"
  - email: "dex2@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "dex2"
    userID: "22222"
  - email: "dex3@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "dex3"
    userID: "33333"
  - email: "googlereview@main.dev-matrix.ebhh-test.k8s.mmertens.metaways.me"
    # $(echo googlereview | htpasswd -BinC 10 admin | cut -d: -f2)
    hash: "$2y$10$sB8gqSnHgiKpPVXx7//FYeZ56aJGUC3fj8XQw31ixZa3GGSXb7sq2"
    username: "googlereview"
    userID: "44444"

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"