# config for synapse
synapse:
  # synapse homeserver config: https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
  # values inside these config are rended by the templating engin. See readme for usage and caveats.
  homeserverConfig:
    server_name: mandant01.example.com # required
    database:
      # # for postgres
      # name: psycopg2

      # or for sqlite
      name: sqlite3
      args:
        database: /data/homeserver.db

    modules:
    # config for shared_secret_auth module. needed for matrix-corporal
    - module: shared_secret_authenticator.SharedSecretAuthProvider
      config:
        m_login_password_support_enabled: true
        # shared_secret: is injected by the entrypoint

  # synapse logging config: https://docs.python.org/3/library/logging.config.html#configuration-dictionary-schema
  # values inside these config are rended by the templating engin. See readme for usage and caveats.
  logConfig:
    loggers:
      # logger for shared_secret_authenticator (optional)
      shared_secret_authenticator:
        level: INFO

  ingress:
    # host name for synapse
    hostname: mandant01.matrix.example.com

  # secrets for synapse, they are injected into the config by the entrypoint.
  # for documentation see: https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
  secrets:
    # existing secret congaing all the synapse secrets. The keys in the secret must be the same as here.
    # existingSecret:
    # or
    registration_shared_secret: 7CFXMRJvHyahcuGSgrHIanrZSWtrbokIWer2sJw1Q81JiS1bAY
    macaroon_secret_key: DD3uwpxP6MrC58dsaaNN3uJepOXC8FtCH3e9q3CgWfhWspC7TL
    form_secret: wHfBnRrR8gNTC3QYmWyBJ44ODLgu4hCyoUnfoy5NzulOq0UBMO
    signing_key: ed25519 a_sCgd KuTfE3bGnylMFwo2sY1Ede1tNN5IVSL4YyqvD/tAP/o
    
  deployment:
    # image to use for synapse, you need to changes if you are using matrix-corporal
    image:
      repository: ocir.example.com/synapse
      tag: specific.tag

  # persistent for media_store and or sqlite db
  pvc:
    accessMode: ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName:
    # or use an existing pvc
    # existingPvc:

# config for element
element:
  ingress:
    # hostname for element
    hostname: mandant01.element.example.com

# config for corporal
corporal:
  # secret for corporal, they are injected into the config by the entrypoint.
  secrets:
    # # existing secret congaing all the corporal secrets. The keys in the secret must be the same as here.
    # existingSecret:
    # or
    # shared secret for shared secret authenticator. Used by matrix-corporal to log into any user account.
    shared_secret: G1zqnmshM3hFaBLEtlRyMtPrSRZ2yqQ5z5zs13kLSAZML4IuY8
    # token to use to authenticate against the matrix corporal api. Tine will need it to push new policies
    authorization_bearer_token: wTWyqxq6drnZ1MoB06pLKqxDwKI90oaXP3rqUWE7qk0K0LIx6N

  # Persistence for policy file. Used to persisted policy.json over restart, but the source of truth should be tine
  pvc:
    enabled: true # can be disabled if pull style policy provider is used
    accessMode: ReadWriteOnce
    resources:
      requests:
        storage: 1Mi # just needs to store a singe json file. The policy contains a list off all managed users: https://github.com/devture/matrix-corporal/blob/master/docs/policy.md
    storageClassName: