version: '3'

vars:
  NAMESPACE: dev-matrix
  KUBE_CONTEXT: '{{.KUBE_CONTEXT | default "ebhh-test"}}'
  DEPLOYMENT_NAME: '{{.DEPLOYMENT_NAME | default "dev"}}'
  BASE_DOMAIN: '{{env "TEST_DEPLOY_BASE_DOMAIN" | default "localhost"}}'
  AUTHORIZATION_BEARER_TOKEN: '{{env "TEST_DEPLOY_AUTHORIZATION_BEARER_TOKEN" | default "CtBEYSx7SPSevNAaux0rDVqWfwYJR7aohvD9SqGtC8NRFPPIy6zphg6rXmgTfVDJ"}}'

tasks:
  test-deploy:
    cmds:
      - BASE_DOMAIN={{.BASE_DOMAIN}} DEPLOYMENT_NAME={{.DEPLOYMENT_NAME}} helmfile -f helmfile.yaml --kube-context {{.KUBE_CONTEXT}} apply

  test-deploy:teardown:
    cmds:
      - helmfile -f helmfile.yaml --kube-context {{.KUBE_CONTEXT}} destroy
      - kubectl delete -n dev-matrix pvc corporal-matrix-{{.DEPLOYMENT_NAME}}-matrix data-postgres-{{.DEPLOYMENT_NAME}}-postgresql-0 redis-data-redis-{{.DEPLOYMENT_NAME}}-master-0

  test-deploy:init-corporal-policy:
    cmds:
      - >
        curl -XPUT -f
        --data '{"schemaVersion": 1}'
        -H "Authorization: Bearer {{.AUTHORIZATION_BEARER_TOKEN}}"
        https://matrix.{{.DEPLOYMENT_NAME}}.{{.BASE_DOMAIN}}/_matrix/corporal/policy