synapse:
  homeserverConfig:
    oidc_providers:
    # tine as oauth provider
    - idp_id: mandant01
      idp_name: mandant01
      issuer: "https://mandant01.example.com/"
      client_id: "matrix"
      client_secret: "WhQxHCu4RDwFBgRHevga6rQJdRsf0S4dWv1RQVqxnYXAlmYrgG"
      scopes: ["openid", "profile", "email"]
      user_profile_method: "userinfo_endpoint"
      user_mapping_provider:
        config:
          localpart_template: "{{ user.preferred_username }}"
          display_name_template: "{{ user.name }}"
          email_template: "{{ user.email }}"
       # important: allows existing user to use oauth without manually changing the external id. Matrix-corporal creates the users if they do not exist, before they create them self.
      allow_existing_users: true

    sso:
      # trust our own hosted element client. Otherwise synapse would show an accept using this client screen
      client_whitelist:
        - https://{{ .Values.element.ingress.hostname }}/
    # keep profile in sync with tine. Matrix-corporal also dose the same. Probably we should only use matrix corporal.
    update_profile_information: true

    # use custom turn server for voip
    turn_uris:
      - turn:turn.example.com?transport=udp
    turn_shared_secret: "n0t4ctuAllymatr1Xd0TorgSshar3d5ecret4obvIousreAsons"
    turn_user_lifetime: 43200 # 12h
    turn_allow_guests: true

element:
  config:
    default_server_config:
      # Set identity server to not vector.im, we do not want to use vector.im as that leaks personal information.
      # We do not want to use an identity server at all. We want users to be able to choose to use vector im. All lookout should already be served by the directory endpoint.
      # todo what server do we want to use here
      m.identity_server:
        base_url: https://sydent.example.com
    # login mask should redirect to tine immediately 
    sso_redirect_options:
      immediate: true

    # use own jitsi server
    jitsi:
      preferred_domain: jitsi.example.com

  deployment:
    # use custom element image
    image:
      repository: ocir.example.com/element
      tag: specific.tag

wellknown:
  # Values inside these config are rended by the templating engin. See readme for usage and caveats.
  client:
    io.element.e2ee:
      # Disable e2ee by default
      default: false
      # Disable automatic e2ee key setup in all cases other than. 1. e2ee is active per default; 2. user is in atlas one encrypted room and dose not have e2ee keys local
      # This is not default option. We patch out element-web and prospectively android and ios as well
      disable_setup: true
