config:
  log:
    setup:
      version: 1
      formatters:
        normal:
          format: "%(asctime)s [%(process)d] %(levelname)-5s %(name)s %(message)s"
      handlers:
        console:
          class: logging.StreamHandler
          formatter: "normal"
      loggers:
        sygnal.access:
          level: "INFO"
      root:
        handlers: ["console"]
        level: "INFO"
      disable_existing_loggers: false
    access:
      x_forwarded_for: false

  http:
    bind_addresses: ['0.0.0.0']
    port: 5000

  metrics:
    prometheus:
      enabled: true
      address: '0.0.0.0'
      port: 8000

  ## Pushkins/Apps #
  #
  # Add a section for every push application here.
  # Specify the pushkey for the application and also the type.
  # For the type, you may specify a fully-qualified Python classname if desired.
  #
  apps:
    # This is an example APNs push configuration
    #
    #com.example.myapp.ios:
    #  type: apns
    #
    #  # Authentication
    #  #
    #  # Two methods of authentication to APNs are currently supported.
    #  #
    #  # You can authenticate using a key:
    #  keyfile: my_key.p8
    #  key_id: MY_KEY_ID
    #  team_id: MY_TEAM_ID
    #  topic: MY_TOPIC
    #
    #  # Or, a certificate can be used instead:
    #  certfile: com.example.myApp_prod_APNS.pem
    #
    #  # This is the maximum number of in-flight requests *for this pushkin*
    #  # before additional notifications will be failed.
    #  # (This is a robustness measure to prevent one pushkin stacking up with
    #  #  queued requests and saturating the inbound connection queue of a load
    #  #  balancer or reverse proxy).
    #  # Defaults to 512 if unset.
    #  #
    #  #inflight_request_limit: 512
    #
    #  # Specifies whether to use the production or sandbox APNs server. Note that
    #  # sandbox tokens should only be used with the sandbox server and vice versa.
    #  #
    #  # Valid options are:
    #  #   * production
    #  #   * sandbox
    #  #
    #  # The default is 'production'. Uncomment to use the sandbox instance.
    #  #platform: sandbox
    #  #
    #  # Specifies whether to convert the device push token from base 64 to hex.
    #  # Defaults to True, set this to False if your client library provides a
    #  # push token in hex format.
    #  #convert_device_token_to_hex: false

    # This is an example GCM/FCM push configuration.
    #
    #com.example.myapp.android:
    #   type: gcm
    #   api_key: your_api_key_for_gcm
    #
    #  # This is the maximum number of connections to GCM servers at any one time
    #  # the default is 20.
    #  #max_connections: 20
    #
    #  # This is the maximum number of in-flight requests *for this pushkin*
    #  # before additional notifications will be failed.
    #  # (This is a robustness measure to prevent one pushkin stacking up with
    #  #  queued requests and saturating the inbound connection queue of a load
    #  #  balancer or reverse proxy).
    #  # Defaults to 512 if unset.
    #  #
    #  #inflight_request_limit: 512
    #
    #  # This allows you to specify additional options to send to Firebase.
    #  #
    #  # Of particular interest, admins who wish to support iOS apps using Firebase
    #  # probably wish to set content_available, and may need to set mutable_content.
    #  # (content_available allows your iOS app to be woken up by data messages,
    #  # and mutable_content allows your notification to be modified by a
    #  # Notification Service app extension).
    #  #
    #  # See https://firebase.google.com/docs/cloud-messaging/http-server-ref
    #  # for the exhaustive list of valid options.
    #  #
    #  # Do not specify `data`, `priority`, `to` or `registration_ids` as they may
    #  # be overwritten or lead to an invalid request.
    #  #
    #  #fcm_options:
    #  #  content_available: true
    #  #  mutable_content: true

secrets:
  existingSecret:

deployment:
  imagePullSecrets: []
  image:
    repository: matrixdotorg/sygnal
  resources: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
  hostname:

inject_entrypoint: false

metadata:
  team:
  name:

debug:
  diagnoseMode:
    enabled: false
    command:
  securityContext:
    enabled: true