{{- if not .Values.livekitJwt.secrets.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "livekitJwt.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "livekitJwt.labels" . | nindent 4 }}
stringData:
  LIVEKIT_URL: {{ .Values.livekitJwt.secrets.LIVEKIT_URL | quote  }}
  LIVEKIT_KEY: {{ .Values.livekitJwt.secrets.LIVEKIT_KEY | quote  }}
  LIVEKIT_SECRET: {{ .Values.livekitJwt.secrets.LIVEKIT_SECRET | quote  }}
{{- end }}