apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-ensure-db
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: "OnFailure"
      containers:
      - image: docker.io/bitnami/postgresql:16.1.0-debian-11-r26
        imagePullPolicy: IfNotPresent
        name: ensure-db
        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-postgresql
                key: postgres-password
          - name: DB_HOST
            value: {{ .Release.Name }}-postgresql
        command:
          - /bin/sh
          - -c
          - psql -h $DB_HOST -U postgres -c "CREATE DATABASE synapse WITH OWNER = 'synapse' TEMPLATE = 'template0' ENCODING = 'UTF-8' LOCALE = 'C'"