apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ .Values.mwconnection.password }}
  postgres-password: {{ .Values.mwconnection.postgresPassword }}
  username: synapse
