{{- if and .Values.corporal.enabled  (not .Values.corporal.secrets.existingSecret)}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "corporal.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "corporal.labels" . | nindent 4 }}
stringData:
  shared_secret: {{ .Values.corporal.secrets.shared_secret | quote  }}
  authorization_bearer_token: {{ .Values.corporal.secrets.authorization_bearer_token | quote  }}
{{- end }}