{{- if .Values.corporal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: client-{{ include "corporal.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "corporal.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 80
      protocol: TCP
      targetPort: client
  selector: {{- include "corporal.matchLabels" . | nindent 4 }}
{{- end }}