apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elementCall.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "elementCall.labels" . | nindent 4 }}
data:
  config.json: |
    {{- tpl ( .Values.elementCall.config | toJson ) . | nindent 4 }}