element:
  # values inside these config are rended by the templating engin. See readme for usage and caveats.
  config:
    default_server_config:
      m.homeserver:
        base_url: "https://{{ .Values.synapse.ingress.hostname }}/"

  extraFrameAncestors: []

  deployment:
    imagePullSecrets: []
    image:
      repository: vectorim/element-web
      tag: v1.11.109
    resources: {}

  ingress:
    annotations:
      kubernetes.io/tls-acme: "true"
    labels:
    enabled: true
    hostname: ""
    tls:
      hostname:

metadata:
  team:
  name: element

debug:
  diagnoseMode:
    element:
      enabled: false
      command:
        - tail
        - -f
        - /dev/null
  securityContext:
    element:
      enabled: true