synapse:
  # values inside these config are rended by the templating engin. See readme for usage and caveats.
  homeserverConfig:
    public_baseurl: "https://{{ .Values.synapse.ingress.hostname }}/"
    pid_file: /data/homeserver.pid
    listeners:
      - port: 8009
        tls: false
        type: http
        x_forwarded: true
        resources:
          - names: [client, federation, static]
            compress: false
      - port: 8093
        type: http
        resources:
        - names: [replication]
      - port: 9000
        tag: metrics
        type: metrics
    database:
      name: psycopg2
      txn_limit: 10000
      args:
        # user: set by entrypoint.py
        # password: set by entrypoint.py
        dbname: # required for postgres
        host: # required for postgres
        port: 5432
        cp_min: 5
        cp_max: 10
    redis:
      enabled: true
      port: 6379
      #host: set by entrypoint.py
      #password: set by entrypoint.py
    instance_map:
      main:
        host: '{{ include "synapse.basename" . }}'
        port: 8093
    log_config: /etc/synapse/log.yaml
    media_store_path: /data/media_store
    registration_shared_secret_path: /etc/synapse/registration_shared_secret
    report_stats: false
    #macaroon_secret_key: set by entrypoint.py
    #form_secret: set by entrypoint.py
    signing_key_path: "/etc/synapse/signing.key"
    trusted_key_servers:
      - server_name: "matrix.org"

  workerConfig:
    worker_app: synapse.app.generic_worker
    # worker_name: gets set to hostname by the entrypoint, if empty

    worker_listeners:
      - type: http
        port: 8009
        x_forwarded: true
        resources:
          - names: [client, federation]

    worker_log_config: /etc/synapse/log.yaml

  worker:
    enabled: true

  # values inside these config are rended by the templating engin. See readme for usage and caveats.
  logConfig:
    version: 1
    formatters:
      precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise
    loggers:
      # This is just here so we can leave `loggers` in the config regardless of whether
      # we configure other loggers below (avoid empty yaml dict error).
      _placeholder:
        level: "INFO"
      synapse.storage.SQL:
          # beware: increasing this to DEBUG will make synapse log sensitive
          # information such as access tokens.
        level: INFO
    root:
      level: INFO
      handlers: [console]
    disable_existing_loggers: false

  deployment:
    imagePullSecrets: []
    image:
      repository: dockerregistry.metaways.net/se/matrix-chart/synapse
      tag: v1.92.3-mw1
    resources: {}

  ingress:
    annotations:
      kubernetes.io/tls-acme: "true"
    enabled: true
    hostname: 

  inject_entrypoint: true

  secrets:
    existingSecret:
    registration_shared_secret: ""
    signing_key: ""
    macaroon_secret_key: ""
    form_secret: ""

  database:
    secret:
    configmap:

  redis:
    secret:
    configmap:

  pvc:
    accessMode: ReadWriteMany
    resources:
      requests:
        storage: 2Gi
    storageClassName:
    existingPvc:

wellknown:
  enabled: true

  # values inside these config are rended by the templating engin. See readme for usage and caveats.
  server:
    m.server: "{{ .Values.synapse.ingress.hostname }}:443"

  # values inside these config are rended by the templating engin. See readme for usage and caveats.
  client:
    m.homeserver:
      base_url: "https://{{ .Values.synapse.ingress.hostname }}/"

  deployment:
    imagePullSecrets: []
    image:
      repository: nginxinc/nginx-unprivileged
      tag: 1.25.3-alpine3.18
    resources: {}

  ingress:
    annotations:
      kubernetes.io/tls-acme: "true"
    enabled: true

corporal:
  enabled: true

  # values inside these config are rended by the templating engin. See readme for usage and caveats.
  config:
    Matrix:
      HomeserverDomainName: "{{ .Values.synapse.homeserverConfig.server_name }}"

      # HomeserverApiEndpoint hack: templating dose not work for json output if the template contains "". As a fix the service name is set as env. And then replaced by the entrypoint 
      HomeserverApiEndpoint: __HOMESERVER_API_ENDPOINT__  # get replaced by the entrypoint to 'http://{{ include "synapse.basename" . }}'
      AuthSharedSecret: __AUTH_SHARED_SECRET__  # get replaced by the entrypoint
      RegistrationSharedSecret: __REGISTRATION_SHARED_SECRET__  # get replaced by the entrypoint
      TimeoutMilliseconds: 45000

    Corporal:
      UserId: "@corporal:{{ .Values.synapse.homeserverConfig.server_name }}"

    Reconciliation:
      RetryIntervalMilliseconds: 30000

    HttpGateway:
      ListenAddress: 0.0.0.0:41080
      TimeoutMilliseconds: 60000
      InternalRESTAuth:
        Enabled: false

    HttpApi:
      Enabled: true
      ListenAddress: 0.0.0.0:41081
      AuthorizationBearerToken: __AUTHORIZATION_BEARER_TOKEN__ # get replaced by the entrypoint
      TimeoutMilliseconds: 15000

    PolicyProvider:
      Type: last_seen_store_policy
      CachePath: /data/policy.json

    Misc:
      Debug: false

  deployment:
    imagePullSecrets: []
    image:
      repository: devture/matrix-corporal
      tag: 2.7.0
    resources: {}

  ingress:
    annotations:
      kubernetes.io/tls-acme: "true"
    enabled: true

  secrets:
    existingSecret:
    shared_secret:
    authorization_bearer_token:

  pvc:
    enabled: true
    accessMode: ReadWriteOnce
    resources:
      requests:
        storage: 1Mi
    storageClassName:

debug:
  diagnoseMode:
    synapse:
      enabled: false
      command:
        - tail
        - -f
        - /dev/null
    synapseWorker:
      enabled: false
      command:
        - tail
        - -f
        - /dev/null
    element:
      enabled: false
      command:
        - tail
        - -f
        - /dev/null
    wellknown:
      enabled: false
      command:
        - tail
        - -f
        - /dev/null
    corporal:
      enabled: false
      command:
        - tail
        - -f
        - /dev/null
  securityContext:
    synapse:
      enabled: true
    element:
      enabled: true
    wellknown:
      enabled: true
    corporal:
      enabled: true

# synapse nginx locations regex
# locations need to start with an / nginx will prepend and ^
synapseEndpoints:
  generic:
    # Sync requests
    - /_matrix/client/(r0|v3)/sync$
    - /_matrix/client/(api/v1|r0|v3)/events$
    - /_matrix/client/(api/v1|r0|v3)/initialSync$
    - /_matrix/client/(api/v1|r0|v3)/rooms/[^/]+/initialSync$

    # Federation requests
    - /_matrix/federation/v1/event/
    - /_matrix/federation/v1/state/
    - /_matrix/federation/v1/state_ids/
    - /_matrix/federation/v1/backfill/
    - /_matrix/federation/v1/get_missing_events/
    - /_matrix/federation/v1/publicRooms
    - /_matrix/federation/v1/query/
    - /_matrix/federation/v1/make_join/
    - /_matrix/federation/v1/make_leave/
    - /_matrix/federation/(v1|v2)/send_join/
    - /_matrix/federation/(v1|v2)/send_leave/
    - /_matrix/federation/(v1|v2)/invite/
    - /_matrix/federation/v1/event_auth/
    - /_matrix/federation/v1/timestamp_to_event/
    - /_matrix/federation/v1/exchange_third_party_invite/
    - /_matrix/federation/v1/user/devices/
    - /_matrix/key/v2/query
    - /_matrix/federation/v1/hierarchy/

    # Inbound federation transaction request
    - /_matrix/federation/v1/send/

    # Client API requests
    - /_matrix/client/(api/v1|r0|v3|unstable)/createRoom$
    - /_matrix/client/(api/v1|r0|v3|unstable)/publicRooms$
    - /_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/joined_members$
    - /_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/context/.*$
    - /_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/members$
    - /_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/state$
    - /_matrix/client/v1/rooms/.*/hierarchy$
    - /_matrix/client/(v1|unstable)/rooms/.*/relations/
    - /_matrix/client/v1/rooms/.*/threads$
    - /_matrix/client/unstable/im.nheko.summary/rooms/.*/summary$
    - /_matrix/client/(r0|v3|unstable)/account/3pid$
    - /_matrix/client/(r0|v3|unstable)/account/whoami$
    - /_matrix/client/(r0|v3|unstable)/devices$
    - /_matrix/client/versions$
    - /_matrix/client/(api/v1|r0|v3|unstable)/voip/turnServer$
    - /_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/event/
    - /_matrix/client/(api/v1|r0|v3|unstable)/joined_rooms$
    - /_matrix/client/v1/rooms/.*/timestamp_to_event$
    - /_matrix/client/(api/v1|r0|v3|unstable/.*)/rooms/.*/aliases
    - /_matrix/client/(api/v1|r0|v3|unstable)/search$
    - /_matrix/client/(r0|v3|unstable)/user/.*/filter(/|$)
    - /_matrix/client/(api/v1|r0|v3|unstable)/directory/room/.*$
    - /_matrix/client/(r0|v3|unstable)/capabilities$
    - /_matrix/client/(r0|v3|unstable)/notifications$

    # Encryption requests
    - /_matrix/client/(r0|v3|unstable)/keys/query$
    - /_matrix/client/(r0|v3|unstable)/keys/changes$
    - /_matrix/client/(r0|v3|unstable)/keys/claim$
    - /_matrix/client/(r0|v3|unstable)/room_keys/
    - /_matrix/client/(r0|v3|unstable)/keys/upload/

    # Registration/login requests
    - /_matrix/client/(api/v1|r0|v3|unstable)/login$
    - /_matrix/client/(r0|v3|unstable)/register$
    - /_matrix/client/(r0|v3|unstable)/register/available$
    - /_matrix/client/v1/register/m.login.registration_token/validity$
    - /_matrix/client/(r0|v3|unstable)/password_policy$

    # Event sending requests
    - /_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/redact
    - /_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/send
    - /_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/state/
    - /_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/(join|invite|leave|ban|unban|kick)$
    - /_matrix/client/(api/v1|r0|v3|unstable)/join/
    - /_matrix/client/(api/v1|r0|v3|unstable)/knock/
    - /_matrix/client/(api/v1|r0|v3|unstable)/profile/

    # Account data requests
    - /_matrix/client/(r0|v3|unstable)/.*/tags
    - /_matrix/client/(r0|v3|unstable)/.*/account_data

    # Receipts requests
    - /_matrix/client/(r0|v3|unstable)/rooms/.*/receipt
    - /_matrix/client/(r0|v3|unstable)/rooms/.*/read_markers

    # Presence requests
    - /_matrix/client/(api/v1|r0|v3|unstable)/presence/

    # User directory search requests
    - /_matrix/client/(r0|v3|unstable)/user_directory/search$