apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "synapse.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "synapse.labels" . | nindent 4 }}
data:
  homeserver.yaml: |
    {{- tpl ( .Values.synapse.homeserverConfig | toYaml ) . | nindent 4 }}

  log.yaml: |
    {{- tpl ( .Values.synapse.logConfig | toYaml ) . | nindent 4 }}

  worker.yaml: |
    {{- tpl ( .Values.synapse.workerConfig | toYaml ) . | nindent 4 }}