apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "synapse.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "synapse.labels" . | nindent 4 }}
    synapse-endpoints: generic
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: {{- include "synapse.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "synapse.labels" . | nindent 8 }}
        synapse-endpoints: generic
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/synapse/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/synapse/secret.yaml") . | sha256sum }}
        {{- if .Values.synapse.inject_entrypoint }}
        checksum/entrypoint: {{ include (print $.Template.BasePath "/synapse/entrypoint.yaml") . | sha256sum }}
        {{- end }}
    spec:
      securityContext:
        runAsUser: 991
        runAsGroup: 991
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
        fsGroupChangePolicy: OnRootMismatch
      {{- if .Values.synapse.deployment.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.synapse.deployment.imagePullSecrets}}
      - {{ toYaml . }}
      {{- end }}
      {{- end }}
      containers:
      - name: synapse
        image: {{ .Values.synapse.deployment.image.repository }}:{{ .Values.synapse.deployment.image.tag }}
        imagePullPolicy: IfNotPresent
        {{- if .Values.debug.diagnoseMode.synapse.enabled }}
        command: {{- toYaml .Values.debug.diagnoseMode.synapse.command  | nindent 12 }}
        {{- else }}
        command:
          - /usr/local/bin/python
          - /entrypoint.py
        {{- end }}
        {{- if .Values.synapse.deployment.resources }}
        resources: {{- toYaml .Values.synapse.deployment.resources | nindent 12 }}
        {{- end }}
        ports:
        - name: matrix
          containerPort: 8009
        - name: metrics
          containerPort: 9000
        - name: replication
          containerPort: 8093
        {{- if .Values.debug.securityContext.synapse.enabled }}
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
        {{- end }}
        env:
        {{- if .Values.synapse.database.secret }}
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.synapse.database.secret }}
              key: username
        {{- end }}
        {{- if .Values.synapse.database.configmap }}
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.synapse.database.configmap }}
              key: HOST
        {{- end }}
        {{- if .Values.synapse.redis.configmap }}
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.synapse.redis.configmap }}
              key: REDIS_HOST
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /etc/synapse/homeserver.yaml
          subPath: homeserver.yaml
          readOnly: 
        - name: config
          mountPath: /etc/synapse/worker.yaml
          subPath: worker.yaml
          readOnly: true
        - name: config
          mountPath: /etc/synapse/log.yaml
          subPath: log.yaml
          readOnly: true
        - name: secret
          mountPath: /etc/synapse/signing.key
          subPath: signing.key
          readOnly: true
        - name: secret
          mountPath: /etc/synapse/registration_shared_secret
          subPath: registration_shared_secret
          readOnly: true 
        - name: secret
          mountPath: /etc/synapse/macaroon_secret_key
          subPath: macaroon_secret_key
          readOnly: true 
        - name: secret  
          mountPath: /etc/synapse/form_secret
          subPath: form_secret
          readOnly: true
        {{- if .Values.synapse.database.secret }}
        - name: database  
          mountPath: /etc/synapse/database_password
          subPath: password
          readOnly: true
        {{- end }}
        {{- if .Values.synapse.redis.secret }}
        - name: redis  
          mountPath: /etc/synapse/redis_password
          subPath: password
          readOnly: true
        {{- end }}
        {{- if .Values.synapse.inject_entrypoint }}
        - name: entrypoint  
          mountPath: /entrypoint.py
          subPath: entrypoint.py
          readOnly: true
        {{- end }}
        {{- if .Values.corporal.enabled }}
        - name: corporal  
          mountPath: /etc/synapse/shared_secret_authenticator_secret
          subPath: shared_secret
          readOnly: true
        {{- end}}
      volumes:
      - name: data
        persistentVolumeClaim:
            claimName: {{ template "synapse.pvc" . }}
      - name: config
        configMap:
          name: {{ template "synapse.basename" . }}
      - name: secret
        secret:
          secretName: {{ template "synapse.secret" . }}
      {{- if .Values.synapse.database.secret }}
      - name: database
        secret:
          secretName: {{ .Values.synapse.database.secret }}
      {{- end }}
      {{- if .Values.synapse.redis.secret }}
      - name: redis
        secret:
          secretName: {{ .Values.synapse.redis.secret }}
      {{- end }}
      {{- if .Values.synapse.inject_entrypoint }}
      - name: entrypoint
        configMap:
          name: entrypoint-{{ template "synapse.basename" . }}
      {{- end }}
      {{- if .Values.corporal.enabled }}
      - name: corporal
        secret:
          secretName: {{ template "corporal.secret" . }}
      {{- end }}