{{- if not .Values.synapse.secrets.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "synapse.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "synapse.labels" . | nindent 4 }}
stringData:
  registration_shared_secret: {{ .Values.synapse.secrets.registration_shared_secret | quote  }}
  signing.key: {{ .Values.synapse.secrets.signing_key | quote }}
  macaroon_secret_key: {{ .Values.synapse.secrets.macaroon_secret_key | quote }}
  form_secret:  {{ .Values.synapse.secrets.form_secret | quote }}
{{- end }}