apiVersion: v1
kind: Service
metadata:
  name: {{ include "synapse.basename" . }}-generic
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "synapse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: matrix
      port: 80
      protocol: TCP
      targetPort: matrix
  selector: {{- include "matchLabels" . | nindent 4 }}
    synapse-endpoints: generic
