apiVersion: v1
kind: Service
metadata:
  name: metrics-{{ include "synapse.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "synapse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: metrics
  selector: {{- include "synapse.matchLabels" . | nindent 4 }}
