{{- if .Values.nginx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nginx.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "nginx.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels: {{- include "nginx.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "nginx.labels" . | nindent 8 }}
      annotations:
        checksum/config-nginx: {{ include (print $.Template.BasePath "/nginx/configmap.yaml") . | sha256sum }}
        checksum/config-wellknown: {{ include (print $.Template.BasePath "/well-known/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      {{- if .Values.nginx.deployment.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.nginx.deployment.imagePullSecrets}}
      - {{ toYaml . }}
      {{- end }}
      {{- end }}
      containers:
      - name: nginx
        image: {{ .Values.nginx.deployment.image.repository }}:{{ .Values.nginx.deployment.image.tag }}
        imagePullPolicy: IfNotPresent
        {{- if .Values.debug.diagnoseMode.nginx.enabled}}
        command: {{- toYaml .Values.debug.diagnoseMode.nginx.command  | nindent 12 }}
        {{- end}}
        {{- if .Values.nginx.deployment.resources }}
        resources: {{- toYaml .Values.nginx.deployment.resources | nindent 12 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 8080
        {{- if .Values.debug.securityContext.nginx.enabled }}
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: false
        - name: config
          mountPath: /usr/share/nginx/html/_matrix/client/v3/capabilities
          subPath: capabilities
          readOnly: true
        {{- if .Values.wellknown.enabled }}
        - name: wellknown
          mountPath: /usr/share/nginx/html/.well-known/matrix/server
          subPath: server
          readOnly: true
        - name: wellknown
          mountPath: /usr/share/nginx/html/.well-known/matrix/client
          subPath: client
          readOnly: true
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "nginx.basename" . }}
      {{- if .Values.wellknown.enabled }}
      - name: wellknown
        configMap:
          name: {{ template "wellknown.basename" . }}
      {{- end }}
      terminationGracePeriodSeconds: 10
{{- end }}